// react/src/components/ui/UiTodoStatus/UiTodoStatus.tsx
import './UiTodoStatus.css';

import React, { Component, Fragment } from 'react';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { TodoStatus } from '../../../domains/todo.model';

export interface IUiTodoStatusProps {
  status: TodoStatus;
}

export class UiTodoStatus extends Component<IUiTodoStatusProps> {
  render() {
    return (
      this.props.status && this.props.status.totalCount ?
        <div className="status">
          <span>{ this.props.status.remainCount }</span>
          /
          <span>{ this.props.status.totalCount }</span>
          { !this.props.status.remainCount ?
            <FontAwesomeIcon icon="smile-beam" className="happy" /> : null }
        </div> : null
    );
  }
}

export default UiTodoStatus;

// angular/src/app/components/ui/ui-todo-status/ui-todo-status.component.ts
import { TodoStatus } from 'App/domains/todo.model';

import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

@Component({
  selector: 'app-ui-todo-status',
  template: `
    <div *ngIf="status" class="status">
      <span>{{ status.remainCount }}</span> / <span>{{ status.totalCount }}</span>
      <fa-icon *ngIf="!status.remainCount" icon="smile-beam" class="happy"></fa-icon>
    </div>
  `,
  styleUrls: ['./ui-todo-status.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class UiTodoStatusComponent {
  @Input() status: TodoStatus;
}
