// react/src/components/ui/UiTodoAdd/UiTodoAdd.tsx
import './UiTodoAdd.css';

import classNames from 'classnames';
import React, { ChangeEvent, Component, KeyboardEvent } from 'react';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

export interface IUiTodoAddProps {
  filterEnabled: boolean;
  filterEnabledChange: (filterEnabled: boolean) => void;
  text: string;
  textChange: (text: string) => void;
  addDisabled: boolean;
  add: (text: string) => void;
}

export class UiTodoAdd extends Component<IUiTodoAddProps> {
  emitFilterEnabled = () => this.props.filterEnabledChange(!this.props.filterEnabled);

  emitText = (event: ChangeEvent<HTMLInputElement>) => {
    this.props.textChange(event.target.value);
  };

  keyDown = (event: KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'Enter') {
      this.emitAdd();
    }
  }

  emitAdd = () => this.props.add(this.props.text);

  get filterClassName() {
    return classNames('filter', { 'filter--disabled': !this.props.filterEnabled });
  }

  render() {
    return (
      <div>
        <button
          className={this.filterClassName}
          onClick={this.emitFilterEnabled}>
          <FontAwesomeIcon icon="filter" />
        </button>

        <input
          className="text"
          placeholder="What needs to be done?"
          type="text"
          value={this.props.text}
          onChange={this.emitText}
          onKeyDown={this.keyDown} />

        <button
          className="add"
          disabled={this.props.addDisabled}
          onClick={this.emitAdd}>
          <FontAwesomeIcon icon="plus" />
        </button>
      </div>
    );
  }
}

export default UiTodoAdd;

// angular/src/app/components/ui/ui-todo-add/ui-todo-add.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-ui-todo-add',
  template: `
    <div>
      <button
        class="filter"
        [class.filter--disabled]="!filterEnabled"
        (click)="emitFilterEnabled()">
        <fa-icon icon="filter"></fa-icon>
      </button>

      <input
        class="text"
        placeholder="What needs to be done?"
        type="text"
        [value]="text"
        (input)="emitText($event.target.value)"
        (keydown.enter)="emitAdd()">

      <button
        class="add"
        [disabled]="addDisabled"
        (click)="emitAdd()">
        <fa-icon icon="plus"></fa-icon>
      </button>
    </div>
  `,
  styleUrls: ['./ui-todo-add.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class UiTodoAddComponent {
  @Input() filterEnabled = false;
  @Output() filterEnabledChange = new EventEmitter<boolean>();

  @Input() text = '';
  @Output() textChange = new EventEmitter<string>();

  @Input() addDisabled = false;

  @Output() add = new EventEmitter<string>();

  emitFilterEnabled() {
    this.filterEnabled = !this.filterEnabled;
    this.filterEnabledChange.emit(this.filterEnabled);
  }

  emitText(text: string) {
    this.text = text;
    this.textChange.emit(this.text);
  }

  emitAdd() {
    if (!this.addDisabled) {
      this.add.emit(this.text);
      this.emitText('');
    }
  }
}

<input
  type="text"
  [value]="text"
  (input)="emitText($event.target.value)">

<button
  (click)="emitAdd()">
  Add
</button>
