// angular/src/app/features/vanilla/components/vanilla-todo/vanilla-todo.component.ts
import { Todo, TodoCategory } from 'App/domains/todo.model';
import {
    editText, filterByCategoryAndText, getStatus, hiddenCategory, isTextFree, todoBuilder, toggleDone
} from 'App/domains/todo.operators';
import { ApiService } from 'App/services/api.service';

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-vanilla-todo',
  template: `
    <div class="top">
      <app-ui-todo-add
        [(filterEnabled)]="filterEnabled"
        [(text)]="text"
        [addDisabled]="addDisabled"
        (add)="add($event)">
      </app-ui-todo-add>
      <app-ui-todo-message [hiddenCategory]="hiddenCategory"></app-ui-todo-message>
    </div>

    <app-ui-todo-list
      [todos]="todosFiltered"
      (toggleDone)="toggleDone($event)"
      (editText)="editText($event)"
      (remove)="remove($event)">
    </app-ui-todo-list>

    <div class="bottom">
      <app-ui-todo-status [status]="status"></app-ui-todo-status>
      <app-ui-todo-switch (categoryChange)="categoryChange($event)"></app-ui-todo-switch>
    </div>
  `,
  styleUrls: ['./vanilla-todo.component.css']
})
export class VanillaTodoComponent implements OnInit {
  todos: Todo[] = [];

  filterEnabled = false;

  text = '';

  category: TodoCategory = 'all';

  get addDisabled() {
    return !isTextFree(this.todos, this.text);
  }

  get hiddenCategory() {
    return hiddenCategory(this.todos, this.text, this.category);
  }

  get filter() {
    return this.filterEnabled ? this.text : '';
  }

  get todosFiltered() {
    return filterByCategoryAndText(this.todos, this.category, this.filter);
  }

  get status() {
    return getStatus(this.todos);
  }

  refresh = () => this.apiService.getTodos().subscribe(todos => this.todos = todos);

  constructor(private apiService: ApiService) { }

  ngOnInit() {
    this.refresh();
  }

  add(text: string) {
    this.apiService.addTodo(todoBuilder(text)).subscribe(this.refresh);
  }

  toggleDone(todo: Todo) {
    this.apiService.updateTodo(toggleDone(todo)).subscribe(this.refresh);
  }

  editText({ todo, text }: { todo: Todo, text: string }) {
    if (text) {
      this.apiService.updateTodo(editText(todo, text)).subscribe(this.refresh);
    } else {
      this.remove(todo);
    }
  }

  remove(todo: Todo) {
    this.apiService.removeTodo(todo).subscribe(this.refresh);
  }

  categoryChange(category: TodoCategory) {
    this.category = category;
  }
}

// react/src/features/Vanilla-todo/Vanilla-todo.tsx
import './Vanilla-todo.css';

import React, { Component, Fragment } from 'react';

import UiTodoList from '../../components/ui/Ui-todo-list/Ui-todo-list';
import { Todo } from '../../domains/todo.model';
import { editText, todoBuilder, toggleDone } from '../../domains/todo.operators';
import { ApiService } from '../../services/api.service';

export interface IVanillaTodoProps {
  todos: Todo[];
}

export class VanillaTodo extends Component<IVanillaTodoProps> {
  state: IVanillaTodoProps = {
    todos: []
  };

  componentDidMount() {
    this.refresh();
  }

  refresh = () => {
    ApiService.getTodos().then(({ data }) => this.setState({ todos: data }));
  }

  add = (text: string) => {
    ApiService.addTodo(todoBuilder(text)).then(this.refresh);
  }

  toggleDone = (todo: Todo) => {
    ApiService.updateTodo(toggleDone(todo)).then(this.refresh);
  }

  editText = (todo: Todo, text: string) => {
    if (text) {
      ApiService.updateTodo(editText(todo, text)).then(this.refresh);
    } else {
      this.remove(todo);
    }
  }

  remove = (todo: Todo) => {
    ApiService.removeTodo(todo).then(this.refresh);
  }

  render() {
    return (
      <Fragment>
        <UiTodoList
          toggleDone={this.toggleDone}
          remove={this.remove}
          editText={this.editText}
          todos={this.state.todos}>
        </UiTodoList>
      </Fragment>
    )
  }
}

export default VanillaTodo;
