// react/src/components/ui/UiTodoMessage/UiTodoMessage.tsx
import './UiTodoMessage.css';

import React, { Component, Fragment } from 'react';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { TodoCategory } from '../../../domains/todo.model';

export interface IUiTodoMessageProps {
  hiddenCategory: TodoCategory | void;
}

export class UiTodoMessage extends Component<IUiTodoMessageProps> {
  render() {
    return (
      <p className="message">
        {this.props.hiddenCategory ?
          <Fragment>
            <FontAwesomeIcon icon="exclamation-triangle" />
            This task appears in the
            "<span className="category">{this.props.hiddenCategory}</span>"
            tab!
          </Fragment>  : null}
        &nbsp;
      </p>
    );
  }
}

export default UiTodoMessage;

// angular/src/app/components/ui/ui-todo-message/ui-todo-message.component.ts
import { TodoCategory } from 'App/domains/todo.model';

import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

@Component({
  selector: 'app-ui-todo-message',
  template: `
    <p class="message">
      <ng-container *ngIf="hiddenCategory">
        <fa-icon icon="exclamation-triangle"></fa-icon>
        This task appears in the
        "<span class="category">{{ hiddenCategory }}</span>"
        tab!
      </ng-container>
      &nbsp;
    </p>
  `,
  styleUrls: ['./ui-todo-message.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class UiTodoMessageComponent {
  @Input() hiddenCategory: TodoCategory;
}
