// angular/src/app/components/ui/ui-todo-category/ui-todo-category.component.ts
import { TodoCategory } from 'App/domains';

import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-ui-todo-category',
  template: `
    <button
      *ngFor="let item of list"
      class="button"
      [class.button--active]="category === item"
      (click)="select(item)">
      {{ item }}
    </button>
  `,
  styleUrls: ['./ui-todo-category.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class UiTodoCategoryComponent {
  @Input() category: TodoCategory = 'all';
  @Output() categoryChange = new EventEmitter<TodoCategory>();

  list: TodoCategory[] = ['all', 'active', 'completed'];

  select(category: TodoCategory) {
    this.categoryChange.emit(category);
  }
}

// react/src/components/ui/UiTodoCategory/UiTodoCategory.tsx
import classNames from 'classnames';
import React, { Component } from 'react';

import { TodoCategory } from '../../../domains';
import styles from './UiTodoCategory.module.css';

export interface IUiTodoCategoryProps {
  category: TodoCategory;
  select: (category: TodoCategory) => void;
}

export class UiTodoCategory extends Component<IUiTodoCategoryProps> {
  list: TodoCategory[] = ['all', 'active', 'completed'];

  className(item: TodoCategory) {
    return classNames(styles['button'], {
      [styles['button--active']]: this.props.category === item
    });
  }

  render() {
    return <div>{this.list.map(item =>
      <button
        key={item}
        className={this.className(item)}
        onClick={() => this.props.select(item)}>
        {item}
      </button>
    )}</div>
  }
}

export default UiTodoCategory;
