// angular/src/app/components/ui/ui-todo-list/ui-todo-list.component.ts
import { Todo } from 'App/domains/todo.model';

import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-ui-todo-list',
  template: `
    <ul *ngIf="todos!.length; else empty" class="list">
      <li *ngFor="let todo of todos; trackBy: trackByTodoId" class="list-item">
        <button (click)="emitToggleDone(todo)">
          <fa-icon [icon]="getToggleIcon(todo)"></fa-icon>
        </button>

        <span
          class="text"
          [class.text--done]="todo.done"
          [appContentEditable]="!todo.done"
          appContentEditableClass="text--edit"
          (appContentEditableChange)="emiEditText(todo, $event)">
          {{ todo.text }}
        </span>

        <button (click)="emitRemove(todo)">
          <fa-icon icon="trash"></fa-icon>
        </button>
      </li>
    </ul>

    <ng-template #empty>
      <div class="hello">
        <fa-icon icon="clipboard-list" size="3x"></fa-icon>
      </div>
    </ng-template>
  `,
  styleUrls: ['./ui-todo-list.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class UiTodoListComponent {
  @Input() todos: Todo[];

  @Output() toggleDone = new EventEmitter<Todo>();
  @Output() editText = new EventEmitter<{ todo: Todo; text: string; }>();
  @Output() remove = new EventEmitter<Todo>();

  emitToggleDone(todo: Todo) {
    this.toggleDone.emit(todo);
  }

  emiEditText(todo: Todo, text: string) {
    this.editText.emit({ todo, text });
  }

  emitRemove(todo: Todo) {
    this.remove.emit(todo);
  }

  trackByTodoId(index: number, todo: Todo) {
    return todo.id;
  }

  getToggleIcon(todo: Todo) {
    return todo.done ? 'toggle-off' : 'toggle-on';
  }
}

<ul *ngIf="todos!.length">
  <li *ngFor="let todo of todos; trackBy: trackByTodoId">
    {{ todo.text }}
    <button (click)="emitToggleDone(todo)">{{ todo.done }}</button>
    <button (click)="emitRemove(todo)">Remove</button>
  </li>
</ul>

// react/src/components/ui/Ui-todo-list/Ui-todo-list.tsx
import './Ui-todo-list.css';

import React, { Component, Fragment } from 'react';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { Todo } from '../../../domains/todo.model';

export interface IUiTodoListProps {
  todos: Todo[];
  toggleDone: (todo: Todo) => void;
  editText: (todo: Todo, text: string) => void;
  remove: (todo: Todo) => void;
}

export class UiTodoList extends Component<IUiTodoListProps> {
  render() {
    return (
      <Fragment>
        { this.props.todos!.length ? 
          <ul className="list">
            { this.props.todos.map(todo => (
              <li key={todo.id} className="list-item">
                <button onClick={() => this.props.toggleDone(todo)}>
                  <FontAwesomeIcon icon={todo.done ? 'toggle-off' : 'toggle-on'}></FontAwesomeIcon>
                </button>

                <span
                  className="text">
                  { todo.text }
                </span>

                <button onClick={() => this.props.remove(todo)}>
                  <FontAwesomeIcon icon="trash"></FontAwesomeIcon>
                </button>
              </li>
            )) }
          </ul>
         : 
          <div className="hello">
            <FontAwesomeIcon icon="clipboard-list" size="3x"></FontAwesomeIcon>
          </div>
        }
      </Fragment>
    );
  }
}

export default UiTodoList;
