// angular/src/app/components/nav/nav.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-nav',
  template: `
    <nav class="nav">
      <a
        *ngFor="let page of pages"
        class="nav-link"
        [routerLink]="page.link"
        routerLinkActive="nav-link--active">
        {{ page.label }}
      </a>
    </nav>
  `,
  styleUrls: ['./nav.component.css']
})
export class NavComponent {
  pages = [
    { link: '/redux', label: 'Redux' },
    { link: '/vanilla', label: 'Vanilla' }
  ];
}

// react/src/components/Nav/Nav.tsx
import React, { Component } from 'react';
import { NavLink } from 'react-router-dom';

import './Nav.css';

export interface INavProps {}

export class Nav extends Component<INavProps> {
  pages = [
    { link: '/redux', label: 'Redux' },
    { link: '/vanilla', label: 'Vanilla' }
  ];

  render() {
    return (
      <nav className="nav">
        {this.pages.map(page => (
          <NavLink
            className="nav-link"
            activeClassName="nav-link--active"
            key={page.link}
            to={page.link}>
            {page.label}
          </NavLink>
        ))}
      </nav>
    );
  }
}

export default Nav;
