// react/src/components/ui/UiTodoSwitch/UiTodoSwitch.tsx
import './UiTodoSwitch.css';

import classNames from 'classnames';
import React, { Component } from 'react';

import { TodoCategory } from '../../../domains/todo.model';

export interface IUiTodoSwitchProps {
  category: TodoCategory;
  select: (category: TodoCategory) => void;
}

export class UiTodoSwitch extends Component<IUiTodoSwitchProps> {
  list: TodoCategory[] = ['all', 'active', 'completed'];

  className(item: TodoCategory) {
    return classNames('button', { 'button--active': this.props.category === item });
  }

  render() {
    return <div>{this.list.map(item =>
      <button
        className={this.className(item)}
        onClick={() => this.props.select(item)}>
        {item}
      </button>
    )}</div>
  }
}

export default UiTodoSwitch;

// angular/src/app/components/ui/ui-todo-switch/ui-todo-switch.component.ts
import { TodoCategory } from 'App/domains/todo.model';

import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-ui-todo-switch',
  template: `
    <button
      *ngFor="let item of list"
      class="button"
      [class.button--active]="category === item"
      (click)="select(item)">
      {{ item }}
    </button>
  `,
  styleUrls: ['./ui-todo-switch.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class UiTodoSwitchComponent {
  @Input() category: TodoCategory = 'all';
  @Output() categoryChange = new EventEmitter<TodoCategory>();

  list: TodoCategory[] = ['all', 'active', 'completed'];

  select(category: TodoCategory) {
    this.category = category;
    this.categoryChange.emit(category);
  }
}
