// angular/src/app/features/vanilla/components/vanilla-todo/vanilla-todo.component.ts
import {
    filterByCategory, getStatus, Todo, todoBuilder, TodoCategory, toggleDone
} from 'App/domains';
import { RestService } from 'App/services/rest.service';

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-vanilla-todo',
  template: `
    <div class="top">
      <app-ui-todo-add
        [(text)]="text"
        (add)="add($event)">
      </app-ui-todo-add>
    </div>

    <app-ui-todo-list
      [todos]="todosFiltered"
      (toggleDone)="toggleDone($event)"
      (remove)="remove($event)">
    </app-ui-todo-list>

    <div class="bottom">
      <app-ui-todo-status [status]="status"></app-ui-todo-status>
      <app-ui-todo-switch [(category)]="category"></app-ui-todo-switch>
    </div>
  `,
  styleUrls: ['./vanilla-todo.component.css']
})
export class VanillaTodoComponent implements OnInit {
  todos: Todo[] = [];

  text = '';

  category: TodoCategory = 'all';

  get todosFiltered() {
    return filterByCategory(this.todos, this.category);
  }

  get status() {
    return getStatus(this.todos);
  }

  refresh = () => this.restService.getTodos().subscribe(todos => this.todos = todos);

  constructor(private restService: RestService) { }

  ngOnInit() {
    this.refresh();
  }

  add(text: string) {
    this.restService.addTodo(todoBuilder(text)).subscribe(this.refresh);
  }

  toggleDone(todo: Todo) {
    this.restService.updateTodo(toggleDone(todo)).subscribe(this.refresh);
  }

  remove(todo: Todo) {
    this.restService.removeTodo(todo).subscribe(this.refresh);
  }
}

// react/src/features/VanillaTodo/VanillaTodo.tsx
import React, { Component, Fragment } from 'react';

import { UiTodoAdd, UiTodoCategory, UiTodoList, UiTodoStatus } from '../../components/ui';
import {
    filterByCategory, getStatus, Todo, todoBuilder, TodoCategory, toggleDone
} from '../../domains';
import { RestService } from '../../shared/RestService';
import styles from './VanillaTodo.module.css';

export interface IVanillaTodoState {
  todos: Todo[];
  text: string;
  category: TodoCategory;
}

export class VanillaTodo extends Component<{}, IVanillaTodoState> {
  state: IVanillaTodoState = {
    todos: [],
    text: '',
    category: 'all'
  };

  get todosFiltered() {
    return filterByCategory(this.state.todos, this.state.category);
  }

  get status() {
    return getStatus(this.state.todos);
  }

  componentDidMount() {
    this.refresh();
  }

  refresh = () => {
    RestService.getTodos().then(({ data }) => this.setState({ todos: data }));
  }

  add = (text: string) => {
    RestService.addTodo(todoBuilder(text)).then(this.refresh);
    this.setState({ text: '' });
  }

  toggleDone = (todo: Todo) => {
    RestService.updateTodo(toggleDone(todo)).then(this.refresh);
  }

  remove = (todo: Todo) => {
    RestService.removeTodo(todo).then(this.refresh);
  }

  textChange = (text: string) => this.setState({ text });

  selectCategory = (category: TodoCategory) => this.setState({ category });

  render() {
    return (
      <Fragment>
        <div className={styles['top']}>
          <UiTodoAdd
            text={this.state.text}
            textChange={this.textChange}
            add={this.add} />
        </div>

        <UiTodoList
          toggleDone={this.toggleDone}
          remove={this.remove}
          todos={this.todosFiltered} />

        <div className={styles['bottom']}>
          <UiTodoStatus status={this.status} />
          <UiTodoCategory category={this.state.category} select={this.selectCategory} />
        </div>
      </Fragment>
    );
  }
}

export default VanillaTodo;
